import Head from "next/head";

const products = [
  {
    id: 1,
    name: "Aroma Diffuser",
    description: "Original product comes in three styles of color, usb charger.",
    price: "$10",
    image: "/images/product-01.png",
  },
  {
    id: 2,
    name: "Lux Aroma Diffuser",
    description: "Original product comes in three styles of color, usb charger.",
    price: "$50",
    image: "/images/product-02.png",
  },
  {
    id: 3,
    name: "Basket INNER BEAUTY",
    description: "Original product comes in three styles of color, usb charger.",
    price: "$70",
    image: "/images/product-03.png",
  },
  {
    id: 4,
    name: "Uplift Handcrafted Soap Bar",
    description: "Original product comes in three styles of color, usb charger.",
    price: "$10",
    image: "/images/product-04.png",
  },
];

export default function Product({ product }) {
  console.log(product);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{JSON.stringify(product)}</div>
      </main>
    </div>
  );
}

export function getServerSideProps(context) {
  const product = products.filter(
    (product) => product.id === parseInt(context.query["product-id"])
  )[0];
  return {
    props: {
      product,
    },
  };
}
