import Head from "next/head";
import Header from "../components/Header";
import Front from "../components/Front";
import ProductCategories from "../components/ProductCategories";
import ShopSection from "../components/ShopSection";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Front />
        <ProductCategories />
        <ShopSection />
      </main>
      <Footer />
    </div>
  );
}
